allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = 'C:/Android/build_cache/dm_build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
